#define C 79
void startupmenu(){
    HANDLE hConsole;
     hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    SetConsoleTextAttribute(hConsole, 15);
    printf("\npress any key to run the program");
    getch();
    system("cls");
    printf("\n\n\n\n\n");Sleep(20);
    printf("                 _");printf("\n");Sleep(20);
    printf("                / \\");printf("\n");Sleep(20);
    printf("                \\_/");printf("\n");Sleep(20);
    printf("                / \\");printf("\n");Sleep(20);
    printf("               /   \\");printf("\n");Sleep(20);
    printf("              /     \\");printf("\n");Sleep(20);
    printf("              \\     /");printf("\n");Sleep(20);
    printf("               \\   /");printf("\n");Sleep(20);
    printf("         /\\    |   |    /\\                                                          __________________________________");printf("\n");Sleep(20);
    printf("        /  \\   |   |   /  \\                                                        |                                  |");printf("\n");Sleep(20);
    printf("        \\   \\__|   |__/   /                                                        |        W E L C O M E  T O        |");printf("\n");Sleep(20);
    printf("         \\               /                                                         |__________________________________|");printf("\n");Sleep(20);
    printf("          \\             /");printf("\n");Sleep(20);
    printf("           \\  \\     /  /                  _________________       ______        ______       _________________       _________________       _________________");printf("\n");Sleep(20);
    printf("            \\_|_____|_/                  |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|  \n");Sleep(20);
    printf("            /         \\                  |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|              ");printf("\n");Sleep(20);
    printf("         __/           \\__               |");SetConsoleTextAttribute(hConsole, C);printf("       __________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("       __________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("       __________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("       __________");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("       _/-----------------\\_             |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("      /---------------------\\            |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|______|");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|__________      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|__________      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|__________ ");printf("\n");Sleep(20);
    printf("      \\                     /            |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, C);printf("             ");SetConsoleTextAttribute(hConsole, C);printf(" ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("       \\                   /             |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, C);printf("             ");SetConsoleTextAttribute(hConsole, C);printf(" ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, C);printf(" ______       ");SetConsoleTextAttribute(hConsole, C);printf("");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("       __________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("__________       ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("__________       ");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                           |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|__________      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|__________       __________|");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      __________|");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|                        ");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|                        ");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("      ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("                 ");SetConsoleTextAttribute(hConsole, 15);printf("|                           ");printf("\n");Sleep(20);
    printf("       ||                 ||             |");SetConsoleTextAttribute(hConsole, C);printf("_________________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("______");SetConsoleTextAttribute(hConsole, 15);printf("|      |");SetConsoleTextAttribute(hConsole, C);printf("______");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("_________________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("_________________");SetConsoleTextAttribute(hConsole, 15);printf("|     |");SetConsoleTextAttribute(hConsole, C);printf("_________________");SetConsoleTextAttribute(hConsole, 15);printf("|                     ");printf("\n");Sleep(20);
    printf("       ||                 ||                                  ");printf("\n");Sleep(20);
    printf("       ||                 ||                                     _______________________________________________________________________");printf("\n");Sleep(20);
    printf("       ||                 ||                                    |                                                                       |");printf("\n");Sleep(20);
    printf("       ||                 ||                                    |        P R E S S  A N Y  B U T T O N  T O  C O N T I N U E !!!        |");printf("\n");Sleep(20);
    printf("       /                   \\                                    |_______________________________________________________________________|");printf("\n");Sleep(20);
    printf("    __/                     \\__");printf("\n");Sleep(20);
    printf("  _/---------------------------\\_");printf("\n");Sleep(20);
    printf(" /-------------------------------\\");printf("\n");Sleep(20);
    printf("||_______________________________||");printf("\n");Sleep(20);
    getch();
    mainmenu();

}
