void startupmenu(){
    printf("\n\n\n\n\n");
    char t;
    printf("                _");printf("\n");
    printf("               / \\");printf("\n");
    printf("               \\_/");printf("\n");
    printf("               / \\");printf("\n");
    printf("              /   \\");printf("\n");
    printf("             /     \\");printf("\n");
    printf("             \\     /");printf("\n");
    printf("              \\   /");printf("\n");
    printf("        /\\    |   |    /\\");printf("\n");
    printf("       /  \\   |   |   /  \\");printf("\n");
    printf("       \\   \\__|   |__/   /");printf("\n");
    printf("        \\               /");printf("\n");
    printf("         \\             /");printf("\n");
    printf("          \\  \\     /  /                 _________________       ______        ______       _________________       _________________       _________________");printf("\n");
    printf("           \\_|_____|_/                  |                 |     |      |      |      |     |                 |     |                 |     |                 |       ");printf("\n");
    printf("           /         \\                  |                 |     |      |      |      |     |                 |     |                 |     |                 | ");printf("\n");
    printf("        __/           \\__               |      ___________|     |      |      |      |     |      ___________|     |      ___________|     |      ___________|");printf("\n");
    printf("      _/-----------------\\_             |     |                 |      |      |      |     |     |                 |     |                 |     |");printf("\n");
    printf("     /---------------------\\            |     |                 |      |______|      |     |     |___________      |     |___________      |     |___________ ");printf("\n");
    printf("     \\                     /            |     |                 |                    |     |                 |     |                 |     |                 |");printf("\n");
    printf("      \\                   /             |     |                 |                    |     |                 |     |                 |     |                 |");printf("\n");
    printf("       ||                 ||             |     |                 |       ______       |     |      ___________|     |___________      |     |___________      |");printf("\n");
    printf("       ||                 ||             |     |                 |      |      |      |     |     |                             |     |                 |     |");printf("\n");
    printf("       ||                 ||             |     |___________      |      |      |      |     |     |___________       ___________|     |      ___________|     |                        ");printf("\n");
    printf("       ||                 ||             |                 |     |      |      |      |     |                 |     |                 |     |                 |                        ");printf("\n");
    printf("       ||                 ||             |                 |     |      |      |      |     |                 |     |                 |     |                 |                           ");printf("\n");
    printf("       ||                 ||             |_________________|     |______|      |______|     |_________________|     |_________________|     |_________________|                     ");printf("\n");
    printf("       ||                 ||");printf("\n");
    printf("       ||                 ||                                             P R E S S  A N Y  B U T T O N  T O  C O N T I N U E !!!");printf("\n");
    printf("       ||                 ||");printf("\n");
    printf("       ||                 ||");printf("\n");
    printf("       /                   \\");printf("\n");
    printf("    __/                     \\__");printf("\n");
    printf("  _/---------------------------\\_");printf("\n");
    printf(" /-------------------------------\\");printf("\n");
    printf("||_______________________________||");printf("\n");
    scanf("%c",&t);
}
